name: YstWorldEdit
version: '0.0.0.1'
main: cf.thdisstudio.ystworldedit.YstWorldEdit
authors: [ Yellowstrawberry ]
description: dafdasfasf
commands:
  /set:
    description: Set
  /wall:
    description: Wall
  /undo:
    description: Undo